### ISSUE TITLE
Tailscale Remains Idle - Clients Inside Network Cannot Access Tailnet

### ISSUE THREAD

**Issue by monorailmedic** [ViktorJp/TAILMON#38]
I have three networks, each with a router connected to Tailscale.  Networks 1 and 2 use GL.iNet hardware, and clients inside those networks can access clients in the other (via subnet routing).  Network 3 uses and ASUS router and Tailmon.  Installed via AMTM, running in userspace mode, subnet routing and exit node advertised (and approved), and Tailscale admin shows all of this with the device connected.

The problem is that the device is always in idle state, and clients inside Network 3/behind this ASUS router cannot reach any devices in the Tailnet.  Reinstalled and attempted kernel mode (rolled back) to no avail.

Have [posted](https://www.snbforums.com/threads/tailmon-v1-0-20-july-27-2024-wireguard-based-tailscale-installer-configurator-and-monitor-now-available-in-amtm.89860/page-25#post-921317) in the SNB forums to no avail.

It's worth noting I do run the WAN Failover script (also via AMTM), so not sure if this is perhaps impacting things, but that's speculative.  Routing table doesn't show any 100* IPs.

Running Tailmon 1.0.20 and Tailscale 1.70.0 on an AX58U running Merlin 388.2_2

**Comment by ViktorJp** [comment]
You have a fairly complex setup, @monorailmedic... TAILMON was only meant to do a basic install of TailScale, and 99% of the time, the needs of users doesn't extend much beyond the router or their immediate subnet.  I would recommend continue plugging away at this on SNB Forums, and possibly dragging ColinTaylor into the mix... he's typically has great advice about these particular questions.
