### ISSUE TITLE
update dnsmasq for the tailscale interface

### ISSUE THREAD

**Issue by mscv** [ViktorJp/TAILMON#39]
Hi,

if possible it would be nice to have a config option to update dnsmasq to answer dns requests from the tailscale interface i.e.

add interface=tailscale0 to /jffs/configs/dnsmasq.conf.add

without this the dns server won't answer dns resolution requests coming from the tailnet (f.ex. when using magicdns with split dns pointing to the asus router's dns resolver).

M.

**Comment by ViktorJp** [comment]
> Hi,
> 
> if possible it would be nice to have a config option to update dnsmasq to answer dns requests from the tailscale interface i.e.
> 
> add interface=tailscale0 to /jffs/configs/dnsmasq.conf.add
> 
> without this the dns server won't answer dns resolution requests coming from the tailnet (f.ex. when using magicdns with split dns pointing to the asus router's dns resolver).
> 
> M.

That may be a good suggestion, but before I go any further... please visit this forum and discuss your findings here:

https://www.snbforums.com/threads/tailmon-v1-0-20-july-27-2024-wireguard-based-tailscale-installer-configurator-and-monitor-now-available-in-amtm.89860/

There may be a chance some configuration issue is preventing things from working correctly, where this statement may not even be needed?  We may have others using it in the same scenario as you, and may have some other suggestions.  If this is something the community is looking for, I will definitely get this added.

Oh, and try tagging @ColinTaylor in this forum... he knows his stuff.

Thank you!

**Comment by ViktorJp** [comment]
Closing issue

**Comment by ViktorJp** [comment]
Closing issue
