### ISSUE TITLE
Use Mullvad exit nodes?

### ISSUE THREAD

**Issue by fehbari** [ViktorJp/TAILMON#41]
My apologies if this isn't the right place to ask about this. I tried registering to SNBForums and ask there, but I was unable to post anything anywhere with the message _"You have insufficient privileges to reply here."_. Even the new user introductions forum won't let me post, as a new user, to introduce myself. 🙃 

Anyway, Tailscale now supports Mullvad exit nodes. It's a very nice integration to get around issues with running Tailscale alongside another VPN. I was able to setup Tailscale on my RT-AX88U Pro with TAILMON and it works great. But I'm not sure how to proceed in making it now use a Mullvad exit node, to cover all devices in my LAN.

I've allowed my router to use the Mullvad subscription in the Tailscale admin panel. But now I need to connect to Tailscale specifying a Mullvad server as the exit note, as documented here: https://tailscale.com/kb/1258/mullvad-exit-nodes?tab=linux

The command I'd need to pass when starting Tailscale are `--exit-node` and `--exit-node-allow-lan-access`, as per the example below.

```
sudo tailscale set --exit-node=<exit-node-name-or-ip> --exit-node-allow-lan-access=true
```

Any advice as to how I might be able to accomplish that with TAILMON? I searched everywhere in `tailmon.sh -setup` settings and only found options to advertise the router itself as an exit node, not use another exit node.

Thanks in advance and appreciate the good work you've done with TAILMON.

**Comment by ViktorJp** [comment]
You can perform this particular action by using the "custom mode" under the "Operating mode configuration" in the setup menu.  This basically gives you full control over the tailscale command lines, to allow you to do these types of things. Good luck, and thanks for bringing the fact that Mullvad is now being supported! :)
